name: Automatically generate documentation
on: 
  push:
    branches: 
    - main
    
jobs:
  build:
    name: Documentation creation with dokka
    runs-on: ubuntu-latest
    steps:
    - name: Small git pull and replace html files for documentation
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SP_DEPLOY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/qwict/StudyPlanet/StudyPlanetAndroid
          rm -rf ./StudyPlanet/build
          git pull
          cp -R ./licenses/* /usr/lib/android-sdk/licenses/
          ./gradlew dokkaHtml
          rm -rf ../StudyPlanetDocumentation/*
          cp -R ./StudyPlanet/build/dokka/html/* ../StudyPlanetDocumentation
    
    - name: Build Stduyplanet to apk
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SP_DEPLOY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/qwict/StudyPlanet/StudyPlanetAndroid
          rm ./StudyPlanet/src/main/res/xml/network_security_config.xml
          cp ../network_security_config.xml ./StudyPlanet/src/main/res/xml/network_security_config.xml
          rm keystore.properties
          rm -rf ./StudyPlanet/build
          cp /var/www/qwict/StudyPlanet/keystore.properties /var/www/qwict/StudyPlanet/StudyPlanetAndroid/
          ./gradlew assembleRelease

    - name: Release APK to Github Releases
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SP_DEPLOY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/qwict/StudyPlanet/StudyPlanetAndroid
          mv /var/www/qwict/StudyPlanet/StudyPlanetAndroid/StudyPlanet/build/outputs/apk/release/StudyPlanet-release.apk /var/www/qwict/StudyPlanet/StudyPlanetAndroid/StudyPlanet/build/outputs/apk/release/StudyPlanet.apk
          gh release create $(echo "$(git log -1 --pretty=%B)" | sed 's/ ->.*//') --title "Study Planet $(echo "$(git log -1 --pretty=%B)" | sed 's/ ->.*//')" --notes "$(echo $(git log -1 --pretty=%B) | sed 's/.*-> //')" './StudyPlanet/build/outputs/apk/release/StudyPlanet.apk'
