name: Automatically generate documentation
on: 
  push:
    branches: 
    - main
    
jobs:
  build:
    name: Documentation creation with dokka
    runs-on: ubuntu-latest
    steps:
    - name: Small git pull and replace html files for documentation
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SP_DEPLOY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/qwict/StudyPlanet/StudyPlanetAndroid
          rm -rf ./StudyPlanet/build
          git pull
          cp -R ./licenses/* /usr/lib/android-sdk/licenses/
          ./gradlew dokkaHtml
          rm -rf ../StudyPlanetDocumentation/*
          cp -R ./StudyPlanet/build/dokka/html/* ../StudyPlanetDocumentation
    
    - name: Build Stduyplanet to apk
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SP_DEPLOY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/qwict/StudyPlanet/StudyPlanetAndroid
          ./gradlew assembleDebug

    - name: Release APK to Github Releases
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SP_DEPLOY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/qwict/StudyPlanet/StudyPlanetAndroid
          gh release create $(echo "$(git log -1 --pretty=%B)" | sed 's/ ->.*//') --title "Study Planet $(echo "$(git log -1 --pretty=%B)" | sed 's/ ->.*//')" --notes "$(echo $(git log -1 --pretty=%B) | sed 's/.*-> //')" './StudyPlanet/build/outputs/apk/debug/StudyPlanet-debug.apk'

